server:
  port: ${APP_PORT}
  servlet:
    context-path: ${API_PREFIX}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off

openapi:
  dev-url: http://localhost:${APP_PORT}${API_PREFIX}
  prod-url: ${PROD_URL}${API_PREFIX}

springdoc:
  api-docs:
    path: ${SWAGGER_PATH}/scheme
  swagger-ui:
    path: ${SWAGGER_PATH}/swagger-ui
    layout: BaseLayout
  enable-spring-security: false
