server:
  port: ${APP_PORT}
  servlet:
    context-path: ${API_PREFIX}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: off
    show-sql: true
    properties:
      hibernate:
        format_sql: true


openapi:
  dev-url: http://localhost:${APP_PORT}${API_PREFIX}
  prod-url: ${PROD_URL}${API_PREFIX}

springdoc:
  api-docs:
    path: ${SWAGGER_PATH}/scheme
  swagger-ui:
    path: ${SWAGGER_PATH}/swagger-ui
    layout: BaseLayout
  enable-spring-security: false

jwt:
  secret:
    access: Y32yhOjyLfnIfc7JZo33fiZek2jCuFQnp8EIceN2KXo0DbyOS9YqeBiQQrmOtL59XyjdgpuVrrxaEC+ejffTQg==
    refresh: 5Cv73gGDb2cE9ow3mWIYUUZrkfny4xwpil74YbMgQt2GSmhZiySEAQwD5L/zS+3RpP80Q5GnPu825K9dW9XXZA==