server:
  port: ${APP_PORT}
  servlet:
    context-path: ${API_PREFIX}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: file:../../../.env[.properties]

