server:
  port: ${APP_PORT}
  servlet:
    context-path: ${API_PREFIX}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: password
  jpa:
    hibernate:
      ddl-auto: update

openapi:
  dev-url: http://localhost:${APP_PORT}${API_PREFIX}
  prod-url: ${PROD_URL}${API_PREFIX}

springdoc:
  api-docs:
    path: /docs/scheme
  swagger-ui:
    path: /docs/swagger-ui
    layout: BaseLayout